ContactForm
Sinned016/Team5-examination pull request #139
Opened 2023-11-13 15:48 UTC by arasvall

2023-11-14 08:20 UTC, Sinned016 approved these changes

2023-11-14 08:22 UTC, Sinned016 requested changes
I ContactPage på rad 14 så har du skrivit "href" vi skulle inte använda oss av det.
Gör det bara till en p tag eller någonting. Vi vill inte länka någonstans.

2023-11-14 11:11 UTC, arasvall commented
href borttagen

2023-11-14 13:27 UTC, Sinned016 approved these changes

2023-11-14 13:28 UTC, Sinned016 commented
Ser bra ut, vi mergar detta imorgon tillsammans för jag tror du är efter i dev nu igen då vi har gjort några uppdateringar.

2023-11-15 09:01 UTC, josefinelihogberg approved these changes

2023-11-15 09:01 UTC, merged