show film's title and date in pop up when delete a booking
Sinned016/Team5-examination pull request #156
Opened 2023-11-16 13:39 UTC by josefinelihogberg

2023-11-16 15:17 UTC, Danblad approved these changes
Well done J!

2023-11-17 09:54 UTC, Sinned016 approved these changes
Ser bra ut men se till att ta bort din "console.log" på rad 38 om allt är klart.

2023-11-17 09:54 UTC, Sinned016 requested changes
Ser bra ut men se till att ta bort din "console.log" på rad 38 om allt är klart.

2023-11-20 08:46 UTC, m4jken approved these changes

2023-11-20 08:48 UTC, Sajo0804 approved these changes

2023-11-20 08:49 UTC, Sajo0804 approved these changes

2023-11-20 08:50 UTC, Sinned016 approved these changes

2023-11-20 08:51 UTC, merged