change urladress to swedish
Sinned016/Team5-examination pull request #157
Opened 2023-11-17 08:19 UTC by arasvall

2023-11-17 09:52 UTC, Sinned016 commented
Allt ser bra ut men jag tycker inte filmdetalj sidan ska heta "filmer" då det bara är 1 film som någon klickar in sig på.

2023-11-17 09:52 UTC, Sinned016 requested changes
Allt ser bra ut men jag tycker inte filmdetalj sidan ska heta "filmer" då det bara är 1 film som någon klickar in sig på.

2023-11-20 08:48 UTC, Sinned016 approved these changes

2023-11-20 08:49 UTC, Sajo0804 approved these changes

2023-11-20 08:49 UTC, merged