change the color in the modal
Sinned016/Team5-examination pull request #91
Opened 2023-11-06 14:56 UTC by arasvall

2023-11-06 15:06 UTC, csmithmountain requested changes
Färgerna ser bra ut. Dock skulle barn vara från 0-12 så det behöver ändras på.

2023-11-08 08:30 UTC, Sinned016 approved these changes

2023-11-08 08:31 UTC, Sajo0804 approved these changes
ålder..

2023-11-08 08:31 UTC, Sajo0804 approved these changes

2023-11-08 08:32 UTC, Sajo0804 approved these changes

2023-11-08 08:32 UTC, m4jken approved these changes

2023-11-08 08:34 UTC, Sajo0804 approved these changes

2023-11-08 08:35 UTC, csmithmountain approved these changes

2023-11-08 08:35 UTC, merged